export const SET_UHF_THEME_LIGHT = 'SET_UHF_THEME::LIGHT';
export const SET_UHF_THEME_DARK = 'SET_UHF_THEME::DARK';
export const SET_UHF_THEME_WHITE = 'SET_UHF_THEME::WHITE';
export const SET_UHF_THEME_LIGHTGRAY = 'SET_UHF_THEME::LIGHTGRAY';
